apiVersion: batch/v1
kind: Job
metadata:
  name: http-long-poll-client-test
spec:
  template:
    spec:
      containers:
      - name: client
        image: curlimages/curl:latest
        command: ["curl", "-v", "http://http-long-poll-backend-service:3000/poll?timeout=5000"]
      restartPolicy: Never